language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  - JULIAVERSION="juliareleases" 
  - JULIAVERSION="julianightlies"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init(); Pkg.clone(pwd())'
  - julia -e 'Pkg.test("Murmur3", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Murmur3")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
